#!/bin/bash

# Auto-Build Environment Setup
# Generated by Planner Agent for Spec 001: Expanded Template Library

set -e

echo "========================================"
echo "Starting Development Environment"
echo "Spec 001: Expanded Template Library"
echo "========================================"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# Wait for service function
wait_for_service() {
    local port=$1
    local name=$2
    local max=30
    local count=0

    echo "Waiting for $name on port $port..."
    while ! nc -z localhost $port 2>/dev/null; do
        count=$((count + 1))
        if [ $count -ge $max ]; then
            echo -e "${RED}$name failed to start${NC}"
            return 1
        fi
        sleep 1
    done
    echo -e "${GREEN}$name ready${NC}"
}

# ============================================
# START SERVICES
# ============================================

# Frontend (React + TypeScript + Vite)
echo ""
echo "Starting Frontend Service..."
cd ./app
npm install 2>&1 | grep -E "(added|up to date)" || echo "Dependencies already installed"
npm run dev &
FRONTEND_PID=$!

# Wait for frontend to be ready
wait_for_service 5173 "Frontend"

# ============================================
# SUMMARY
# ============================================

echo ""
echo "========================================"
echo "Environment Ready!"
echo "========================================"
echo ""
echo "Services:"
echo "  Frontend:  http://localhost:5173"
echo ""
echo "Process IDs:"
echo "  Frontend: $FRONTEND_PID"
echo ""
echo "To stop all services, run:"
echo "  kill $FRONTEND_PID"
echo ""
echo "========================================"
echo "You can now begin implementing subtasks"
echo "========================================"
