#!/bin/bash

# Auto-Build Environment Setup
# Generated by Planner Agent for Mobile-Responsive Design

set -e

echo "========================================"
echo "Starting Development Environment"
echo "Punchline X - Mobile Responsive Design"
echo "========================================"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# Wait for service function
wait_for_service() {
    local port=$1
    local name=$2
    local max=30
    local count=0

    echo "Waiting for $name on port $port..."
    while ! nc -z localhost $port 2>/dev/null; do
        count=$((count + 1))
        if [ $count -ge $max ]; then
            echo -e "${RED}$name failed to start${NC}"
            return 1
        fi
        sleep 1
    done
    echo -e "${GREEN}$name ready${NC}"
}

# ============================================
# START SERVICES
# ============================================

echo ""
echo "Starting Punchline X (React + Vite)..."
cd app && npm run dev &
wait_for_service 5173 "Punchline X"

# ============================================
# SUMMARY
# ============================================

echo ""
echo "========================================"
echo "Environment Ready!"
echo "========================================"
echo ""
echo "Services:"
echo "  Punchline X: http://localhost:5173"
echo ""
echo "Mobile Testing Tips:"
echo "  - Use Chrome DevTools responsive mode (Cmd+Shift+M)"
echo "  - Test viewports: 375px (iPhone), 768px (tablet), 1920px (desktop)"
echo "  - Verify touch targets are 44x44px minimum"
echo "  - Test both portrait and landscape orientations"
echo ""
