#!/bin/bash

# Auto-Build Environment Setup
# Generated by Planner Agent for Score Explanation Cards feature

set -e

echo "========================================"
echo "Starting Punchline X Development Environment"
echo "========================================"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# Wait for service function
wait_for_service() {
    local port=$1
    local name=$2
    local max=30
    local count=0

    echo "Waiting for $name on port $port..."
    while ! nc -z localhost $port 2>/dev/null; do
        count=$((count + 1))
        if [ $count -ge $max ]; then
            echo -e "${RED}$name failed to start${NC}"
            return 1
        fi
        sleep 1
    done
    echo -e "${GREEN}$name ready${NC}"
}

# ============================================
# START SERVICES
# ============================================

# Frontend Application (React + Vite)
echo -e "${YELLOW}Starting frontend application...${NC}"
cd app && npm run dev &
wait_for_service 3000 "Frontend Application"

# ============================================
# SUMMARY
# ============================================

echo ""
echo "========================================"
echo "Environment Ready!"
echo "========================================"
echo ""
echo "Services:"
echo "  Frontend Application: http://localhost:3000"
echo ""
echo "Next Steps:"
echo "  1. Open http://localhost:3000 in your browser"
echo "  2. Navigate to scoring results to see score breakdown"
echo "  3. Verify explanation card integration works"
echo ""
echo "To stop services: Press Ctrl+C"
echo ""
