#!/bin/bash

# Auto-Build Environment Setup for AI Tweet Rewriter
# Generated by Planner Agent

set -e

echo "========================================"
echo "Starting Development Environment"
echo "AI Tweet Rewriter Feature"
echo "========================================"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# Wait for service function
wait_for_service() {
    local port=$1
    local name=$2
    local max=30
    local count=0

    echo "Waiting for $name on port $port..."
    while ! nc -z localhost $port 2>/dev/null; do
        count=$((count + 1))
        if [ $count -ge $max ]; then
            echo -e "${RED}$name failed to start${NC}"
            return 1
        fi
        sleep 1
    done
    echo -e "${GREEN}$name ready${NC}"
}

# ============================================
# VERIFY ENVIRONMENT
# ============================================

echo ""
echo "Checking environment..."

if [ ! -f "app/.env.local" ]; then
    echo -e "${RED}Error: app/.env.local not found${NC}"
    echo "Please create app/.env.local with ZAI_API_KEY"
    exit 1
fi

if ! grep -q "ZAI_API_KEY" app/.env.local; then
    echo -e "${YELLOW}Warning: ZAI_API_KEY not found in app/.env.local${NC}"
    echo "The AI features will not work without this API key"
fi

echo -e "${GREEN}Environment verified${NC}"

# ============================================
# START SERVICES
# ============================================

echo ""
echo "Starting services..."

# Change to app directory
cd app

# Start Bun proxy server in background
echo "Starting Bun proxy server (port 3001)..."
bun run src/server/ai-proxy.ts &
BUN_PID=$!

# Wait for Bun server to be ready
wait_for_service 3001 "Bun Proxy Server"

# Start React dev server in background
echo "Starting React dev server (port 5173)..."
npm run dev &
VITE_PID=$!

# Wait for React dev server
wait_for_service 5173 "React Dev Server"

# ============================================
# SUMMARY
# ============================================

echo ""
echo "========================================"
echo "Environment Ready!"
echo "========================================"
echo ""
echo "Services:"
echo "  Bun Proxy:  http://localhost:3001"
echo "  Frontend:   http://localhost:5173"
echo ""
echo "API Endpoints:"
echo "  POST /api/generate-hooks"
echo "  POST /api/rewrite-tweet (to be implemented)"
echo ""
echo "Press Ctrl+C to stop all services"
echo ""

# Trap Ctrl+C to kill all background processes
trap "kill $BUN_PID $VITE_PID 2>/dev/null; exit" INT TERM

# Wait for any process to exit
wait
