#!/bin/bash

# Auto-Build Environment Setup
# Generated by Planner Agent for Spec 012: Codex PR Fix #2

set -e

echo "========================================"
echo "Starting Development Environment"
echo "========================================"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# Wait for service function
wait_for_service() {
    local port=$1
    local name=$2
    local max=30
    local count=0

    echo "Waiting for $name on port $port..."
    while ! nc -z localhost $port 2>/dev/null; do
        count=$((count + 1))
        if [ $count -ge $max ]; then
            echo -e "${RED}$name failed to start${NC}"
            return 1
        fi
        sleep 1
    done
    echo -e "${GREEN}$name ready${NC}"
}

# ============================================
# INVESTIGATION WORKFLOW - NO SERVICES NEEDED
# ============================================

echo ""
echo -e "${YELLOW}Investigation Workflow${NC}"
echo "This task uses GitHub CLI to fetch PR data."
echo "No development server required for initial phases."
echo ""

# Verify GitHub CLI is authenticated
echo "Checking GitHub CLI authentication..."
if gh auth status &>/dev/null; then
    echo -e "${GREEN}✓ GitHub CLI authenticated${NC}"
else
    echo -e "${RED}✗ GitHub CLI not authenticated${NC}"
    echo "Please run: gh auth login"
    exit 1
fi

# ============================================
# OPTIONAL: START DEV SERVER FOR TESTING
# ============================================

read -p "Start development server? (y/N) " -n 1 -r
echo
if [[ $REPLY =~ ^[Yy]$ ]]; then
    echo "Starting punchline-x development server..."
    cd app
    npm run dev &
    cd ..
    wait_for_service 5173 "punchline-x"

    echo ""
    echo "========================================"
    echo "Environment Ready!"
    echo "========================================"
    echo ""
    echo "Services:"
    echo "  punchline-x: http://localhost:5173"
    echo ""
else
    echo ""
    echo "========================================"
    echo "Ready for Investigation!"
    echo "========================================"
    echo ""
    echo "Use GitHub CLI commands to fetch PR data:"
    echo "  gh pr view 4 --json reviews,comments"
    echo "  gh api repos/AmbitiousRealism2025/punchline-x/pulls/4/reviews/3633255069/comments"
    echo ""
fi
