#!/bin/bash

# Auto-Build Environment Setup
# Generated by Planner Agent - Thread Builder Feature

set -e

echo "========================================"
echo "Starting Development Environment"
echo "Thread Builder Feature - Spec 004"
echo "========================================"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# Wait for service function
wait_for_service() {
    local port=$1
    local name=$2
    local max=30
    local count=0

    echo "Waiting for $name on port $port..."
    while ! nc -z localhost $port 2>/dev/null; do
        count=$((count + 1))
        if [ $count -ge $max ]; then
            echo -e "${RED}$name failed to start${NC}"
            return 1
        fi
        sleep 1
    done
    echo -e "${GREEN}$name ready${NC}"
}

# ============================================
# INSTALL DEPENDENCIES (if needed)
# ============================================

echo ""
echo "Checking dependencies..."
cd app

# Check if node_modules exists
if [ ! -d "node_modules" ]; then
    echo -e "${YELLOW}Installing npm dependencies...${NC}"
    npm install
fi

# Check if @dnd-kit packages are installed
if ! npm list @dnd-kit/core >/dev/null 2>&1; then
    echo -e "${YELLOW}Installing @dnd-kit packages...${NC}"
    npm install @dnd-kit/core @dnd-kit/sortable @dnd-kit/utilities
fi

# ============================================
# START SERVICES
# ============================================

echo ""
echo "Starting frontend development server..."

# Kill any existing process on port 5173
lsof -ti:5173 | xargs kill -9 2>/dev/null || true

# Start Vite dev server in background
npm run dev &

# Wait for frontend to be ready
wait_for_service 5173 "Frontend (Vite)"

# ============================================
# SUMMARY
# ============================================

echo ""
echo "========================================"
echo "Environment Ready!"
echo "========================================"
echo ""
echo "Services:"
echo "  Frontend:  http://localhost:5173"
echo ""
echo "Thread Builder Implementation:"
echo "  - Phase 1: Dependencies Setup"
echo "  - Phase 2: Thread State Management"
echo "  - Phase 3: Thread UI Components"
echo "  - Phase 4: Thread Scoring Logic"
echo "  - Phase 5: Thread Suggestions"
echo "  - Phase 6: App Integration"
echo ""
echo "To view in browser:"
echo "  open http://localhost:5173"
echo ""
echo "To stop services:"
echo "  pkill -f 'vite'"
echo ""
