#!/bin/bash

# Auto-Build Environment Setup - Voice Profile & Personalization
# Generated by Planner Agent

set -e

echo "========================================"
echo "Starting Development Environment"
echo "========================================"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# Wait for service function
wait_for_service() {
    local port=$1
    local name=$2
    local max=30
    local count=0

    echo "Waiting for $name on port $port..."
    while ! nc -z localhost $port 2>/dev/null; do
        count=$((count + 1))
        if [ $count -ge $max ]; then
            echo -e "${RED}$name failed to start${NC}"
            return 1
        fi
        sleep 1
    done
    echo -e "${GREEN}$name ready${NC}"
}

# ============================================
# CHECK ENVIRONMENT
# ============================================

if [ ! -f "app/package.json" ]; then
    echo -e "${RED}Error: app/package.json not found${NC}"
    echo "Make sure you're running this from the project root"
    exit 1
fi

if [ -z "$ZAI_API_KEY" ]; then
    echo -e "${YELLOW}Warning: ZAI_API_KEY not set${NC}"
    echo "AI proxy may not work without it"
fi

# ============================================
# INSTALL DEPENDENCIES
# ============================================

echo ""
echo "Installing dependencies..."
cd app

if ! command -v bun &> /dev/null; then
    echo -e "${RED}Error: bun is not installed${NC}"
    echo "Install bun from https://bun.sh"
    exit 1
fi

bun install

cd ..

# ============================================
# START SERVICES
# ============================================

echo ""
echo "Starting services..."

# AI Proxy Server (Port 3001)
echo "Starting AI Proxy Server..."
cd app/src/server
bun run ai-proxy.ts &
AI_PROXY_PID=$!
cd ../../..

# Wait for AI proxy
wait_for_service 3001 "AI Proxy Server"

# Frontend (Port 5173)
echo "Starting Frontend (Vite)..."
cd app
bun run dev &
FRONTEND_PID=$!
cd ..

# Wait for frontend
wait_for_service 5173 "Frontend"

# ============================================
# SUMMARY
# ============================================

echo ""
echo "========================================"
echo "Environment Ready!"
echo "========================================"
echo ""
echo "Services:"
echo "  AI Proxy:  http://localhost:3001"
echo "  Frontend:  http://localhost:5173"
echo ""
echo "Environment Variables:"
echo "  ZAI_API_KEY: ${ZAI_API_KEY:0:10}..."
echo ""
echo "To stop services:"
echo "  kill $AI_PROXY_PID $FRONTEND_PID"
echo ""
echo "Press Ctrl+C to stop all services"
echo ""

# Keep script running
wait
